spring:
  application:
    name: analyticsapp
  config:
    import: optional:configserver:http://localhost:8888
    activate:
      on-profile : dev
---
spring:
  config:
    activate:
      on-profile : test
server:
  port: 9000
